import pg from "pg";
import { createHmac, randomUUID } from "node:crypto";
import { createApiKey } from "../../auth/src/api-keys.js";
import type { AuthPrincipal, ServerDependencies } from "../../../apps/api/src/server.js";
import type { TurnStreamEvent } from "../../codex-runtime/src/turns.js";
import { weightedUnits } from "../../quota/src/budget.js";

export class PlatformRepository implements ServerDependencies {
  readonly pool: pg.Pool;
  constructor(databaseUrl: string, private readonly pepper: string) { this.pool = new pg.Pool({ connectionString: databaseUrl, max: 20 }); }

  async authenticate(token: string): Promise<AuthPrincipal | null> {
    const digest = createHmac("sha256", this.pepper).update(token).digest("hex");
    const result = await this.pool.query(`SELECT u.id AS user_id,u.role,p.id AS profile_id FROM api_keys k JOIN users u ON u.id=k.user_id JOIN LATERAL (SELECT id FROM profiles WHERE user_id=u.id AND status='active' ORDER BY created_at LIMIT 1) p ON true WHERE k.digest=$1 AND k.status='active' AND (k.expires_at IS NULL OR k.expires_at>now()) AND u.status='active'`, [digest]);
    const row = result.rows[0]; return row ? { userId: row.user_id, profileId: row.profile_id, role: row.role } : null;
  }

  async profile(profileId: string): Promise<{ codexHome: string; cwd: string }> {
    const result = await this.pool.query(`SELECT codex_home,COALESCE(config->>'cwd',$2) cwd FROM profiles WHERE id=$1 AND status='active'`, [profileId, process.cwd()]);
    if (!result.rows[0]) throw new Error("Active profile not found"); return { codexHome: result.rows[0].codex_home, cwd: result.rows[0].cwd };
  }

  async reserve(principal: AuthPrincipal, estimate: number, requestId: string): Promise<{ allowed: boolean; reservationId?: string; reason?: string }> {
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN"); await client.query("SELECT pg_advisory_xact_lock(hashtext($1))", [principal.userId]);
      await client.query(`INSERT INTO requests(id,idempotency_key,user_id,profile_id,backend_id,model,status,started_at,measurement_source,confidence) VALUES($1,$1,$2,$3,'codex-chatgpt','pending','queued',now(),'estimated','low') ON CONFLICT(idempotency_key) DO NOTHING`, [requestId, principal.userId, principal.profileId]);
      const limits = await client.query(`SELECT b.id,b.metric,b.limit_value,b.mode,b.tolerance_basis_points,COALESCE(SUM(CASE WHEN r.status IN ('reserved','reconciled') THEN COALESCE(r.actual,r.reserved) ELSE 0 END),0)::bigint used FROM budget_limits b JOIN usage_cycles c ON c.id=b.cycle_id LEFT JOIN quota_reservations r ON r.budget_limit_id=b.id WHERE b.enabled AND c.status='active' AND (b.subject_type='user' AND b.subject_id=$1 OR b.subject_type='profile' AND b.subject_id=$2) GROUP BY b.id`, [principal.userId, principal.profileId]);
      for (const limit of limits.rows) { const used = Number(limit.used), maximum = Number(limit.limit_value) * (1 + Number(limit.tolerance_basis_points) / 10_000); if (limit.mode === "hard" && used + estimate > maximum) { await client.query("UPDATE requests SET status='blocked',finished_at=now(),error_code='quota_exceeded' WHERE id=$1", [requestId]); await client.query("COMMIT"); return { allowed: false, reason: `${limit.metric} quota exhausted` }; } }
      if (limits.rows.length) await client.query(`INSERT INTO quota_reservations(id,request_id,budget_limit_id,reserved,status,expires_at) SELECT gen_random_uuid(),$1,id,$2,'reserved',now()+interval '10 minutes' FROM budget_limits WHERE id=ANY($3::uuid[])`, [requestId, estimate, limits.rows.map(row => row.id)]);
      await client.query("UPDATE requests SET status='running' WHERE id=$1", [requestId]); await client.query("COMMIT"); return { allowed: true, reservationId: requestId };
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }

  async reconcile(requestId: string | undefined, event: TurnStreamEvent): Promise<void> {
    if (event.type !== "completed" || !requestId) return;
    const usage = event.result.usage; const input = Number(usage.inputTokens ?? usage.input_tokens ?? 0), output = Number(usage.outputTokens ?? usage.output_tokens ?? 0), cached = Number(usage.cachedInputTokens ?? usage.cached_input_tokens ?? 0), reasoning = Number(usage.reasoningTokens ?? usage.reasoning_tokens ?? 0); const units = weightedUnits(input, output, cached, reasoning);
    const client = await this.pool.connect(); try { await client.query("BEGIN"); await client.query(`UPDATE requests SET status='success',finished_at=now(),duration_ms=EXTRACT(EPOCH FROM(now()-started_at))*1000,input_tokens=$2,output_tokens=$3,cached_input_tokens=$4,reasoning_tokens=$5,weighted_units=$6,tools=$7,compactions=$8,measurement_source='codex',confidence='high' WHERE id=$1`, [requestId, input, output, cached, reasoning, units, JSON.stringify(event.result.tools), event.result.compactions]); await client.query(`UPDATE quota_reservations SET actual=$2,status='reconciled' WHERE request_id=$1`, [requestId, units]); await client.query("COMMIT"); } catch(error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }
  async failRequest(requestId:string,cancelled:boolean,error:string):Promise<void>{await this.pool.query(`UPDATE requests SET status=$2,finished_at=now(),duration_ms=EXTRACT(EPOCH FROM(now()-started_at))*1000,error_code=$3,metadata=metadata||$4::jsonb WHERE id=$1`,[requestId,cancelled?"cancelled":"error",cancelled?"client_cancelled":"runtime_error",JSON.stringify({error:error.slice(0,500)})]);await this.pool.query(`UPDATE quota_reservations SET status='released',actual=0 WHERE request_id=$1 AND status='reserved'`,[requestId])}
  async resolveSession(principal:AuthPrincipal,sessionId:string|undefined,model:string):Promise<{sessionId:string;threadId?:string}>{if(sessionId){const row=(await this.pool.query(`SELECT id,codex_thread_id FROM sessions WHERE id=$1 AND user_id=$2 AND profile_id=$3 AND status='active'`,[sessionId,principal.userId,principal.profileId])).rows[0];if(!row)throw new Error("Session not found or not owned by caller");return{sessionId:row.id,threadId:row.codex_thread_id??undefined}}const row=(await this.pool.query(`INSERT INTO sessions(user_id,profile_id,title,model) VALUES($1,$2,$3,$4) RETURNING id`,[principal.userId,principal.profileId,"New conversation",model])).rows[0];return{sessionId:row.id}}
  async bindThread(sessionId:string,threadId:string):Promise<void>{await this.pool.query(`UPDATE sessions SET codex_thread_id=$2,updated_at=now() WHERE id=$1 AND (codex_thread_id IS NULL OR codex_thread_id=$2)`,[sessionId,threadId])}

  async adminSummary(): Promise<Record<string, number>> {
    const result = await this.pool.query(`SELECT (SELECT count(*) FROM users)::int users,(SELECT count(*) FROM requests WHERE status='running')::int active_requests,(SELECT count(*) FROM requests WHERE status='blocked')::int blocked,COALESCE((SELECT sum(weighted_units) FROM requests WHERE status='success'),0)::bigint weighted_units,COALESCE((SELECT sum(estimated_cost_micros) FROM requests WHERE status='success'),0)::bigint estimated_cost_micros`); const row=result.rows[0]; return { users: row.users, activeRequests: Number(row.active_requests), queueDepth: 0, blocked: Number(row.blocked), weightedUnits: Number(row.weighted_units), estimatedCostMicros: Number(row.estimated_cost_micros) };
  }
  async adminUsage(limit: number, offset: number): Promise<unknown[]> {
    const result = await this.pool.query(`SELECT u.name user_name,r.model,r.backend_id,count(*)::int requests,sum(r.weighted_units)::bigint weighted_units,sum(r.estimated_cost_micros)::bigint cost_micros,count(*) FILTER(WHERE r.status='error')::int errors FROM requests r JOIN users u ON u.id=r.user_id GROUP BY u.name,r.model,r.backend_id ORDER BY weighted_units DESC LIMIT $1 OFFSET $2`,[limit,offset]); return result.rows.map(row=>({user:row.user_name,model:row.model,backend:row.backend_id,requests:row.requests,weightedUnits:Number(row.weighted_units),costMicros:Number(row.cost_micros),errors:row.errors}));
  }
  async adminAudit(limit: number, offset: number): Promise<unknown[]> {
    const result=await this.pool.query(`SELECT id,event,target_type,created_at,metadata FROM audit_events ORDER BY created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]); return result.rows.map(row=>({id:row.id,event:row.event,targetType:row.target_type,createdAt:row.created_at,metadata:row.metadata}));
  }
  async adminUsers():Promise<unknown[]>{const r=await this.pool.query(`SELECT u.id,u.name,u.status,u.role,p.id profile_id,p.name profile_name,p.backend_id,COALESCE(sum(q.weighted_units),0)::bigint weighted_units FROM users u LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN requests q ON q.user_id=u.id GROUP BY u.id,p.id ORDER BY u.created_at`);return r.rows.map(x=>({...x,weighted_units:Number(x.weighted_units)}))}
  async createUser(input:{name:string;role:string;codexHome:string;cwd?:string}):Promise<unknown>{if(!["user","operator","admin","owner"].includes(input.role))throw new Error("Invalid role");const client=await this.pool.connect();try{await client.query("BEGIN");const user=(await client.query(`INSERT INTO users(name,role) VALUES($1,$2) RETURNING id,name,status,role`,[input.name,input.role])).rows[0];const profile=(await client.query(`INSERT INTO profiles(user_id,name,codex_home,backend_id,config) VALUES($1,'default',$2,'codex-chatgpt',$3) RETURNING id,name,backend_id`,[user.id,input.codexHome,{cwd:input.cwd??process.cwd()}])).rows[0];const key=createApiKey(user.id,this.pepper);await client.query(`INSERT INTO api_keys(id,user_id,prefix,digest,status,created_at) VALUES($1,$2,$3,$4,'active',$5)`,[key.record.id,user.id,key.record.prefix,key.record.digest,key.record.createdAt]);await client.query(`INSERT INTO audit_events(actor_user_id,event,target_type,target_id) VALUES($1,'user.created','user',$1)`,[user.id]);await client.query("COMMIT");return{user,profile,apiKey:{id:key.record.id,prefix:key.record.prefix,secret:key.secret}}}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
  async rotateKey(userId:string):Promise<unknown>{const key=createApiKey(userId,this.pepper);await this.pool.query(`INSERT INTO api_keys(id,user_id,prefix,digest,status,created_at) VALUES($1,$2,$3,$4,'active',$5)`,[key.record.id,userId,key.record.prefix,key.record.digest,key.record.createdAt]);await this.pool.query(`INSERT INTO audit_events(actor_user_id,event,target_type,target_id) VALUES($1,'api_key.created','api_key',$2)`,[userId,key.record.id]);return{id:key.record.id,prefix:key.record.prefix,secret:key.secret}}
  async revokeKey(keyId:string):Promise<void>{await this.pool.query(`UPDATE api_keys SET status='revoked',revoked_at=now() WHERE id=$1`,[keyId]);await this.pool.query(`INSERT INTO audit_events(event,target_type,target_id) VALUES('api_key.revoked','api_key',$1)`,[keyId])}
  async setUserStatus(userId:string,status:string):Promise<void>{if(!["active","suspended","blocked"].includes(status))throw new Error("Invalid status");await this.pool.query(`UPDATE users SET status=$2 WHERE id=$1`,[userId,status]);await this.pool.query(`INSERT INTO audit_events(event,target_type,target_id,metadata) VALUES('user.status_changed','user',$1,$2)`,[userId,{status}])}
  async createCycle(input:{name:string;kind:string;startsAt:string;endsAt?:string}):Promise<unknown>{if(!["day","week","month","rolling","custom"].includes(input.kind))throw new Error("Invalid cycle kind");return(await this.pool.query(`INSERT INTO usage_cycles(name,kind,starts_at,ends_at) VALUES($1,$2,$3,$4) RETURNING *`,[input.name,input.kind,input.startsAt,input.endsAt??null])).rows[0]}
  async resetCycle(cycleId:string):Promise<unknown>{const client=await this.pool.connect();try{await client.query("BEGIN");const old=(await client.query(`UPDATE usage_cycles SET status='closed',ends_at=COALESCE(ends_at,now()) WHERE id=$1 RETURNING *`,[cycleId])).rows[0];if(!old)throw new Error("Cycle not found");const next=(await client.query(`INSERT INTO usage_cycles(name,kind,starts_at,window_seconds,metadata) VALUES($1,$2,now(),$3,$4) RETURNING *`,[old.name,old.kind,old.window_seconds,{resetFrom:cycleId}])).rows[0];await client.query(`INSERT INTO budget_limits(cycle_id,subject_type,subject_id,model,metric,limit_value,mode,warning_percent,tolerance_basis_points,enabled) SELECT $1,subject_type,subject_id,model,metric,limit_value,mode,warning_percent,tolerance_basis_points,enabled FROM budget_limits WHERE cycle_id=$2`,[next.id,cycleId]);await client.query(`INSERT INTO audit_events(event,target_type,target_id,metadata) VALUES('cycle.reset','usage_cycle',$1,$2)`,[next.id,{previous:cycleId}]);await client.query("COMMIT");return next}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}
  async usageFor(userId:string):Promise<unknown>{const r=await this.pool.query(`SELECT count(*)::int requests,COALESCE(sum(weighted_units),0)::bigint weighted_units,COALESCE(sum(input_tokens),0)::bigint input_tokens,COALESCE(sum(output_tokens),0)::bigint output_tokens FROM requests WHERE user_id=$1`,[userId]);return Object.fromEntries(Object.entries(r.rows[0]).map(([k,v])=>[k,Number(v)]))}
  async exportUsage(format:"json"|"csv"):Promise<string>{const rows=(await this.pool.query(`SELECT id,user_id,profile_id,backend_id,model,status,started_at,finished_at,input_tokens,output_tokens,cached_input_tokens,reasoning_tokens,weighted_units FROM requests ORDER BY started_at DESC`)).rows;if(format==="json")return JSON.stringify(rows);const headers=Object.keys(rows[0]??{id:""});const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;return[headers.map(cell).join(","),...rows.map(r=>headers.map(h=>cell(r[h])).join(","))].join("\n")}
}
