export class ApiClient {
  constructor(private base = "/api", private token = sessionStorage.getItem("adminToken") ?? "") {}
  setToken(token: string) { this.token = token; sessionStorage.setItem("adminToken", token); }
  async get<T>(path: string): Promise<T> { const response = await fetch(this.base + path, { headers: { Authorization: `Bearer ${this.token}` } }); if (!response.ok) throw new Error(await response.text()); return response.json(); }
  async send<T>(path: string, method: string, body?: unknown): Promise<T> { const response = await fetch(this.base + path, { method, headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); if (!response.ok) throw new Error(await response.text()); return response.json(); }
  /** Incremental SSE consumer adapted from OpenCodex chat/outbound (MIT, d1f544b). */
  async streamChat(body:unknown,onDelta:(text:string)=>void):Promise<void>{const response=await fetch(this.base+"/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${this.token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());if(!response.body)throw new Error("Resposta sem stream");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const blocks=buffer.split("\n\n");buffer=blocks.pop()??"";for(const block of blocks)for(const line of block.split("\n")){if(!line.startsWith("data:"))continue;const payload=line.slice(5).trim();if(!payload||payload==="[DONE]")continue;const event=JSON.parse(payload);const delta=event.choices?.[0]?.delta?.content;if(typeof delta==="string")onDelta(delta);if(event.error)throw new Error(event.error.message??"Falha no stream")}if(done)break}}
}
export const api = new ApiClient();
