import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{api}from"./api.js";
import"./styles.css";

type Tab="chat"|"overview"|"users"|"keys"|"profiles"|"quotas"|"backends"|"audit";
type Summary={users:number;activeRequests:number;queueDepth:number;blocked:number;weightedUnits:number;estimatedCostMicros:number};
type Usage={user:string;model:string;backend:string;requests:number;weightedUnits:number;costMicros:number;errors:number};
type Audit={id:string;event:string;targetType:string;createdAt:string};
type User={id:string;name:string;status:string;role:string;profile_id:string;profile_name:string;backend_id:string;weighted_units:number};
type Model={id:string;displayName?:string;description?:string;defaultReasoningEffort?:string;supportedReasoningEfforts?:{reasoningEffort:string}[]};
type Session={id:string;title:string;model:string;threadId?:string;updatedAt:string};
type Message={role:"user"|"assistant";text:string};
type Principal={userId:string;profileId:string;role:"user"|"operator"|"admin"|"owner"};
const nav:[Tab,string][]=[["chat","Chat"],["overview","Visão geral"],["users","Usuários"],["keys","API keys"],["profiles","Perfis"],["quotas","Cotas e ciclos"],["backends","Modelos"],["audit","Auditoria"]];

function App(){
 const[token,setToken]=useState(sessionStorage.getItem("adminToken")??"");
 const[tab,setTab]=useState<Tab>("chat"),[principal,setPrincipal]=useState<Principal>(),[summary,setSummary]=useState<Summary>(),[usage,setUsage]=useState<Usage[]>([]),[audit,setAudit]=useState<Audit[]>([]),[users,setUsers]=useState<User[]>([]),[models,setModels]=useState<Model[]>([]),[error,setError]=useState("");
 async function load(){try{api.setToken(token);const[me,m,own]=await Promise.all([api.get<Principal>("/v1/me"),api.get<{data:Model[]}>("/v1/models"),api.get<Record<string,number>>("/v1/me/usage")]);setPrincipal(me);setModels(m.data);if(me.role==="admin"||me.role==="owner"){const[s,u,a,us]=await Promise.all([api.get<Summary>("/admin/summary"),api.get<{data:Usage[]}>("/admin/usage?limit=50"),api.get<{data:Audit[]}>("/admin/audit?limit=50"),api.get<{data:User[]}>("/admin/users")]);setSummary(s);setUsage(u.data);setAudit(a.data);setUsers(us.data)}else{setSummary({users:1,activeRequests:0,queueDepth:0,blocked:0,weightedUnits:Number(own.weighted_units??own.weightedUnits??0),estimatedCostMicros:0});setUsage([]);setAudit([]);setUsers([])}setError("")}catch(e){setPrincipal(undefined);setSummary(undefined);setError(String(e))}}
 useEffect(()=>{if(token)void load()},[token]);
 if(!summary)return <main className="login"><section><h1>AIWrapper</h1><p>Entre com sua chave individual</p><input aria-label="AIWrapper API key" type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="aiw_..."/><button onClick={load}>Entrar</button>{error&&<pre>{error}</pre>}</section></main>;
 const allowedNav=principal?.role==="admin"||principal?.role==="owner"?nav:nav.filter(([id])=>id==="chat"||id==="overview");
 return <div className="shell"><aside><h1>AIWrapper</h1>{allowedNav.map(([id,label])=><button data-testid={`nav-${id}`} className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}<button data-testid="logout" onClick={()=>{sessionStorage.removeItem("adminToken");location.reload()}}>Sair</button></aside><main className={tab==="chat"?"chat-main":""}>{error&&<pre className="error">{error}</pre>}{tab==="chat"?<Chat models={models}/>:<><header><h2>{nav.find(x=>x[0]===tab)?.[1]}</h2><button onClick={load}>Atualizar</button></header>{tab==="overview"&&<Overview summary={summary} usage={usage}/>} {tab==="users"&&<Users users={users} reload={load}/>} {tab==="keys"&&<Keys users={users}/>} {tab==="profiles"&&<Profiles users={users}/>} {tab==="quotas"&&<Overview summary={summary} usage={usage}/>} {tab==="backends"&&<Backends models={models}/>} {tab==="audit"&&<AuditView rows={audit}/>}</>}</main></div>;
}

function Chat({models}:{models:Model[]}){
 const[sessions,setSessions]=useState<Session[]>([]),[sessionId,setSessionId]=useState<string>(),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[model,setModel]=useState(models[0]?.id??"gpt-5.6-sol"),[effort,setEffort]=useState("low"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function refresh(){const r=await api.get<{data:Session[]}>("/v1/sessions");setSessions(r.data)}
 useEffect(()=>{void refresh()},[]);
 async function open(id:string){setSessionId(id);setBusy(true);try{const r=await api.get<any>(`/v1/sessions/${id}`);const out:Message[]=[];for(const turn of r.thread?.turns??[])for(const item of turn.items??[]){if(item.type==="userMessage")out.push({role:"user",text:(item.content??[]).map((x:any)=>x.text??"").join("\n")});if(item.type==="agentMessage")out.push({role:"assistant",text:item.text??""})}setMessages(out);setModel(r.session.model)}finally{setBusy(false)}}
 function fresh(){setSessionId(undefined);setMessages([]);setInput("");setError("")}
 async function send(){const text=input.trim();if(!text||busy)return;setInput("");setMessages(old=>[...old,{role:"user",text},{role:"assistant",text:""}]);setBusy(true);setError("");let generated="";try{await api.streamChat({model,stream:true,reasoning_effort:effort,metadata:sessionId?{session_id:sessionId}:{},messages:[{role:"user",content:text}]},delta=>{generated+=delta;setMessages(old=>[...old.slice(0,-1),{role:"assistant",text:generated}])});await refresh();if(!sessionId){const latest=await api.get<{data:Session[]}>("/v1/sessions");setSessionId(latest.data[0]?.id)}}catch(e){setError(String(e))}finally{setBusy(false)}}
 const efforts=models.find(x=>x.id===model)?.supportedReasoningEfforts?.map(x=>x.reasoningEffort)??["low","medium","high","xhigh"];
 return <div className="chat-layout"><section className="conversation-rail"><button className="new-chat" onClick={fresh}>+ Nova conversa</button><h3>Conversas</h3>{sessions.map(s=><button className={sessionId===s.id?"selected":""} onClick={()=>void open(s.id)} key={s.id}><strong>{s.title||"Nova conversa"}</strong><small>{s.model}</small></button>)}</section><section className="conversation"><div className="chat-toolbar"><select aria-label="Modelo" value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.displayName??m.id}</option>)}</select><select aria-label="Effort" value={effort} onChange={e=>setEffort(e.target.value)}>{efforts.map(x=><option key={x}>{x}</option>)}</select></div><div className="messages">{messages.length===0&&<div className="empty-chat"><h2>O que vamos construir?</h2><p>Esta conversa passa pelo AIWrapper e entra no seu ledger.</p></div>}{messages.map((m,i)=><article className={`message ${m.role}`} key={i}><span>{m.role==="user"?"Você":"Codex"}</span><div>{m.text||<i>Respondendo...</i>}</div></article>)}</div>{error&&<pre className="error">{error}</pre>}<div className="composer"><textarea aria-label="Mensagem" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Envie uma mensagem ao Codex..."/><button disabled={busy||!input.trim()} onClick={()=>void send()}>{busy?"Executando...":"Enviar"}</button></div></section></div>;
}

function Overview({summary,usage}:{summary:Summary;usage:Usage[]}){return <><div className="cards"><Card label="Usuários" value={summary.users}/><Card label="Ativas" value={summary.activeRequests}/><Card label="Fila" value={summary.queueDepth}/><Card label="Bloqueios" value={summary.blocked}/><Card label="Unidades" value={summary.weightedUnits.toLocaleString()}/></div><UsageTable rows={usage}/></>}
function Users({users,reload}:{users:User[];reload:()=>Promise<void>}){const[name,setName]=useState(""),[home,setHome]=useState(""),[key,setKey]=useState("");async function create(){const r=await api.send<any>("/admin/users","POST",{name,role:"user",codexHome:home});setKey(r.apiKey.secret);await reload()}return <><Panel title="Criar usuário"><div className="form-row"><input placeholder="Nome" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="CODEX_HOME" value={home} onChange={e=>setHome(e.target.value)}/><button disabled={!name||!home} onClick={()=>void create()}>Criar</button></div>{key&&<code className="secret">{key}</code>}</Panel><Panel title="Usuários"><table><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.role}</td><td>{u.status}</td><td>{Number(u.weighted_units).toLocaleString()} un.</td></tr>)}</tbody></table></Panel></>}
function Keys({users}:{users:User[]}){const[key,setKey]=useState("");async function rotate(id:string){const r=await api.send<any>(`/admin/users/${id}/keys`,"POST");setKey(r.secret)}return <Panel title="API keys">{key&&<code className="secret">{key}</code>}<table><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td><button onClick={()=>void rotate(u.id)}>Gerar nova chave</button></td></tr>)}</tbody></table></Panel>}
function Profiles({users}:{users:User[]}){return <Panel title="Perfis CODEX_HOME"><table><tbody>{users.map(u=><tr key={u.profile_id}><td>{u.name}</td><td>{u.profile_name}</td><td>{u.backend_id}</td></tr>)}</tbody></table></Panel>}
function Backends({models}:{models:Model[]}){return <Panel title={`${models.length} modelos disponíveis`}><div className="model-grid">{models.map(m=><article key={m.id}><strong>{m.displayName??m.id}</strong><code>{m.id}</code><p>{m.description}</p></article>)}</div></Panel>}
function AuditView({rows}:{rows:Audit[]}){return <Panel title="Auditoria"><table><tbody>{rows.map(r=><tr key={r.id}><td>{r.event}</td><td>{r.targetType}</td><td>{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table></Panel>}
function UsageTable({rows}:{rows:Usage[]}){return <Panel title="Consumo"><table><thead><tr><th>Usuário</th><th>Modelo</th><th>Backend</th><th>Requests</th><th>Unidades</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.user}</td><td>{r.model}</td><td>{r.backend}</td><td>{r.requests}</td><td>{Number(r.weightedUnits).toLocaleString()}</td></tr>)}</tbody></table></Panel>}
function Card({label,value}:{label:string;value:string|number}){return <section className="card"><span>{label}</span><strong>{value}</strong></section>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h3>{title}</h3>{children}</section>}
createRoot(document.getElementById("root")!).render(<App/>);
